const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let token=localStorage.getItem("tf_token")||"",user=JSON.parse(localStorage.getItem("tf_user")||"null"),projects=[],users=[],activeProject=null,activeTask=null,authMode="login",boardFilter="all";
const statusInfo={todo:{title:"To do",cls:"todo"},progress:{title:"In progress",cls:"progress"},done:{title:"Done",cls:"done"}};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const date=s=>s?new Date(s).toLocaleDateString(undefined,{month:"short",day:"numeric"}):"No due date";
async function api(url,opt={}){const headers={"Content-Type":"application/json",...(opt.headers||{})};if(token)headers.Authorization="Bearer "+token;const r=await fetch("/api"+url,{...opt,headers}),d=await r.json().catch(()=>({message:"Unexpected response"}));if(!r.ok)throw Error(d.message||"Request failed");return d}
let toastTimer;function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),2400)}
function modal(id){$("#backdrop").classList.add("show");$("#"+id).classList.add("show")}function close(){ $("#backdrop").classList.remove("show");$$(".modal").forEach(m=>m.classList.remove("show"))}
$("#backdrop").onclick=close;$$("[data-close]").forEach(b=>b.onclick=close);
function updateUser(){if(user){$("#userName").textContent=user.name;$("#userEmail").textContent=user.email;$("#avatar").textContent=user.name[0].toUpperCase();$("#logoutBtn").style.display="block"}else{$("#userName").textContent="Guest";$("#userEmail").textContent="Sign in to begin";$("#avatar").textContent="?";$("#logoutBtn").style.display="none"}}
function authUI(){const reg=authMode==="register";$("#authTitle").textContent=reg?"Create your account":"Welcome back";$("#authSub").textContent=reg?"Start organizing your team's work.":"Sign in to continue to Taskflow.";$("#authNameWrap").classList.toggle("hidden",!reg);$("#authNameWrap input").required=reg;$("#authSubmit").textContent=reg?"Create account →":"Sign in →";$("#switchLabel").textContent=reg?"Already have an account?":"New to Taskflow?";$("#switchAuth").textContent=reg?"Sign in":"Create an account";$("#authError").textContent=""}
$("#switchAuth").onclick=()=>{authMode=authMode==="login"?"register":"login";authUI()};
$("#authForm").onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));try{const d=await api("/auth/"+(authMode==="login"?"login":"register"),{method:"POST",body:JSON.stringify(b)});token=d.token;user=d.user;localStorage.setItem("tf_token",token);localStorage.setItem("tf_user",JSON.stringify(user));close();updateUser();await loadProjects();toast("Welcome to Taskflow, "+user.name.split(" ")[0]+"!")}catch(x){$("#authError").textContent=x.message}};
$("#logoutBtn").onclick=()=>{token="";user=null;projects=[];activeProject=null;localStorage.removeItem("tf_token");localStorage.removeItem("tf_user");updateUser();showProjects();$("#projectGrid").innerHTML='<div class="empty">Sign in to view your projects.</div>';modal("authModal");authMode="login";authUI()};
$("#newProjectBtn").onclick=()=>{if(!user){authMode="login";authUI();return modal("authModal")}$("#projectError").textContent="";modal("projectModal")};
$("#projectForm").onsubmit=async e=>{e.preventDefault();try{await api("/projects",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});e.currentTarget.reset();close();await loadProjects();toast("Project created.")}catch(x){$("#projectError").textContent=x.message}};
async function loadProjects(){if(!token){$("#projectGrid").innerHTML='<div class="empty">Sign in to create and manage projects.</div>';return}try{projects=await api("/projects");renderProjects()}catch(e){toast(e.message)}}
function renderProjects(){$("#projectCount").textContent=projects.length+" project"+(projects.length===1?"":"s");if(!projects.length){$("#projectGrid").innerHTML='<div class="empty">No projects yet. Create your first project to get started.</div>';return}$("#projectGrid").innerHTML=projects.map((p,i)=>`<article class="project-card" data-project="${p._id}"><div class="project-icon">${["✳","◈","▧","✦"][i%4]}</div><h4>${esc(p.name)}</h4><p>${esc(p.description||"A shared space to plan and track work.")}</p><div class="project-foot"><span>▤ ${p.tasks.length} task${p.tasks.length===1?"":"s"}</span><div class="mini-avatars">${(p.members||[]).slice(0,4).map(m=>`<span class="mini-avatar" title="${esc(m.name)}">${esc(m.name[0].toUpperCase())}</span>`).join("")}</div></div></article>`).join("");$$("[data-project]").forEach(c=>c.onclick=()=>openProject(c.dataset.project))}
function showProjects(){$("#projectsView").classList.remove("hidden");$("#boardView").classList.add("hidden");$("#pageTitle").textContent="Your projects";$("#crumbTitle").textContent="Projects"}
$("#backProjects").onclick=()=>{activeProject=null;showProjects();loadProjects()};
async function openProject(id){try{activeProject=await api("/projects/"+id);users=await api("/users");$("#projectsView").classList.add("hidden");$("#boardView").classList.remove("hidden");$("#pageTitle").textContent=activeProject.name;$("#crumbTitle").textContent=activeProject.name;$("#boardDescription").textContent=activeProject.description||"Your team's shared project board.";renderBoard()}catch(e){toast(e.message)}}
$$("[data-filter]").forEach(b=>b.onclick=()=>{boardFilter=b.dataset.filter;$$("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));renderBoard()});
function renderBoard(){if(!activeProject)return;const cols=["todo","progress","done"];let tasks=activeProject.tasks||[];if(boardFilter==="mine")tasks=tasks.filter(t=>t.assignee&&String(t.assignee._id||t.assignee)===String(user.id));$("#kanban").innerHTML=cols.map(s=>{const ts=tasks.filter(t=>t.status===s);return `<div class="kanban-column ${statusInfo[s].cls}"><div class="column-head"><div class="column-title"><span class="status-dot"></span>${statusInfo[s].title}<span class="task-count">${ts.length}</span></div><button class="add-inline" data-add-status="${s}">＋</button></div><div class="task-list">${ts.map(taskCard).join("")}</div></div>`}).join("");$$("[data-task]").forEach(c=>c.onclick=()=>openTask(c.dataset.task));$$("[data-add-status]").forEach(b=>b.onclick=()=>openTaskForm(b.dataset.addStatus))}
function taskCard(t){const ass=t.assignee;return `<article class="task-card" data-task="${t._id}"><span class="priority ${t.priority}">${t.priority} priority</span><h4>${esc(t.title)}</h4>${t.description?`<p>${esc(t.description)}</p>`:""}<div class="task-foot"><span>◷ ${date(t.dueDate)}</span><span class="assignee">${ass?`<span class="mini-avatar">${esc(ass.name[0].toUpperCase())}</span>${esc(ass.name.split(" ")[0])}`:"Unassigned"}</span></div><div class="task-comments">☰ ${t.comments?.length||0} comments</div></article>`}
$("#addTaskBtn").onclick=()=>openTaskForm("todo");
function openTaskForm(status){if(!activeProject)return;$("#taskForm").reset();$("#taskError").textContent="";$("#taskModalTitle").textContent="Add a task";const sel=$("#assigneeSelect");sel.innerHTML='<option value="">Unassigned</option>'+users.map(u=>`<option value="${u._id}">${esc(u.name)} · ${esc(u.email)}</option>`).join("");$("#taskForm").dataset.status=status;modal("taskModal")}
$("#taskForm").onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));b.status=e.currentTarget.dataset.status||"todo";if(!b.assignee)delete b.assignee;if(!b.dueDate)delete b.dueDate;try{activeProject=await api(`/projects/${activeProject._id}/tasks`,{method:"POST",body:JSON.stringify(b)});close();renderBoard();toast("Task added.")}catch(x){$("#taskError").textContent=x.message}};
async function openTask(id){activeTask=activeProject.tasks.find(t=>t._id===id);if(!activeTask)return;$("#detailTitle").textContent=activeTask.title;$("#detailDescription").textContent=activeTask.description||"No description provided.";$("#detailMeta").innerHTML=`<span>${esc(activeTask.priority)} priority</span><span>Due ${date(activeTask.dueDate)}</span><span>${activeTask.assignee?"Assigned to "+esc(activeTask.assignee.name):"Unassigned"}</span>`;$("#detailStatus").value=activeTask.status;$("#detailError").textContent="";renderComments();modal("detailModal")}
function renderComments(){$("#commentList").innerHTML=activeTask.comments?.length?activeTask.comments.map(c=>`<div class="comment"><b>${esc(c.name||c.user?.name||"Teammate")}</b><p>${esc(c.text)}</p><small>${new Date(c.createdAt).toLocaleString()}</small></div>`).join(""):'<p class="muted">No comments yet. Start the conversation.</p>'}
$("#detailStatus").onchange=async e=>{try{activeProject=await api(`/projects/${activeProject._id}/tasks/${activeTask._id}`,{method:"PATCH",body:JSON.stringify({status:e.target.value})});activeTask=activeProject.tasks.find(t=>t._id===activeTask._id);renderBoard();toast("Task status updated.")}catch(x){$("#detailError").textContent=x.message}};
$("#commentForm").onsubmit=async e=>{e.preventDefault();const text=new FormData(e.currentTarget).get("text");try{activeProject=await api(`/projects/${activeProject._id}/tasks/${activeTask._id}/comments`,{method:"POST",body:JSON.stringify({text})});activeTask=activeProject.tasks.find(t=>t._id===activeTask._id);e.currentTarget.reset();renderComments();renderBoard()}catch(x){$("#detailError").textContent=x.message}};
$("#deleteTaskBtn").onclick=async()=>{if(!confirm("Delete this task?"))return;try{activeProject=await api(`/projects/${activeProject._id}/tasks/${activeTask._id}`,{method:"DELETE"});close();renderBoard();toast("Task deleted.")}catch(x){$("#detailError").textContent=x.message}};
$("#addMemberBtn").onclick=()=>{if(!activeProject)return;$("#inviteError").textContent="";modal("inviteModal")};
$("#inviteForm").onsubmit=async e=>{e.preventDefault();try{activeProject=await api(`/projects/${activeProject._id}/members`,{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});close();renderBoard();toast("Teammate added.")}catch(x){$("#inviteError").textContent=x.message}};
$("#navProjects").onclick=()=>{showProjects();loadProjects()};
updateUser();if(!token){modal("authModal");authMode="login";authUI()}else loadProjects();