require("dotenv").config();
const express=require("express"), mongoose=require("mongoose"), cors=require("cors"), bcrypt=require("bcryptjs"), jwt=require("jsonwebtoken"), path=require("path");
const app=express();app.use(cors());app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
mongoose.connect(process.env.MONGO_URI||"mongodb://127.0.0.1:27017/codealpha_projects").then(()=>console.log("MongoDB connected")).catch(e=>console.error(e.message));
const User=mongoose.model("User",new mongoose.Schema({name:{type:String,required:true},email:{type:String,unique:true,lowercase:true},passwordHash:{type:String,required:true}},{timestamps:true}));
const commentSchema=new mongoose.Schema({user:{type:mongoose.Schema.Types.ObjectId,ref:"User"},name:String,text:{type:String,required:true}},{timestamps:true});
const taskSchema=new mongoose.Schema({title:{type:String,required:true},description:String,status:{type:String,enum:["todo","progress","done"],default:"todo"},priority:{type:String,enum:["Low","Medium","High"],default:"Medium"},assignee:{type:mongoose.Schema.Types.ObjectId,ref:"User",default:null},dueDate:Date,comments:[commentSchema]},{timestamps:true});
const projectSchema=new mongoose.Schema({name:{type:String,required:true},description:String,owner:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true},members:[{type:mongoose.Schema.Types.ObjectId,ref:"User"}],tasks:[taskSchema]},{timestamps:true});
const Project=mongoose.model("Project",projectSchema);
const secret=()=>process.env.JWT_SECRET||"dev_secret_change_me";
function auth(req,res,next){const t=(req.headers.authorization||"").replace(/^Bearer\\s+/i,"");try{if(!t)throw 0;req.userId=jwt.verify(t,secret()).id;next()}catch{return res.status(401).json({message:"Please sign in."})}}
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
app.get("/api/health",(req,res)=>res.json({status:"ok"}));
app.post("/api/auth/register",asyncRoute(async(req,res)=>{const {name,email,password}=req.body;if(!name?.trim()||!email||!password||password.length<6)return res.status(400).json({message:"Name, email and password (6+ characters) are required."});if(await User.findOne({email:email.toLowerCase()}))return res.status(409).json({message:"Email already registered."});const u=await User.create({name:name.trim(),email:email.toLowerCase(),passwordHash:await bcrypt.hash(password,12)});res.status(201).json({token:jwt.sign({id:u._id},secret(),{expiresIn:"7d"}),user:{id:u._id,name:u.name,email:u.email}})}));
app.post("/api/auth/login",asyncRoute(async(req,res)=>{const u=await User.findOne({email:(req.body.email||"").toLowerCase()});if(!u||!await bcrypt.compare(req.body.password||"",u.passwordHash))return res.status(401).json({message:"Incorrect email or password."});res.json({token:jwt.sign({id:u._id},secret(),{expiresIn:"7d"}),user:{id:u._id,name:u.name,email:u.email}})}));
app.get("/api/users",auth,asyncRoute(async(req,res)=>res.json(await User.find().select("name email").sort("name"))));
app.get("/api/projects",auth,asyncRoute(async(req,res)=>res.json(await Project.find({$or:[{owner:req.userId},{members:req.userId}]}).populate("owner","name email").populate("members","name email").populate("tasks.assignee","name email").sort({updatedAt:-1}))));
app.post("/api/projects",auth,asyncRoute(async(req,res)=>{if(!req.body.name?.trim())return res.status(400).json({message:"Project name is required."});const p=await Project.create({name:req.body.name.trim(),description:req.body.description||"",owner:req.userId,members:[req.userId],tasks:[]});res.status(201).json(await p.populate(["owner","members"]))}));
async function getProject(id,userId){const p=await Project.findById(id).populate("owner","name email").populate("members","name email").populate("tasks.assignee","name email").populate("tasks.comments.user","name");if(!p)return null;if(!p.members.some(m=>String(m._id)===String(userId))&&String(p.owner._id)!==String(userId))return false;return p}
app.get("/api/projects/:id",auth,asyncRoute(async(req,res)=>{const p=await getProject(req.params.id,req.userId);if(p===null)return res.status(404).json({message:"Project not found."});if(p===false)return res.status(403).json({message:"Access denied."});res.json(p)}));
app.patch("/api/projects/:id",auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({message:"Project not found."});if(String(p.owner)!==String(req.userId))return res.status(403).json({message:"Only the project owner can edit project details."});if(req.body.name)p.name=req.body.name.trim();if(req.body.description!==undefined)p.description=req.body.description;await p.save();res.json(p)}));
app.post("/api/projects/:id/members",auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({message:"Project not found."});if(String(p.owner)!==String(req.userId))return res.status(403).json({message:"Only the owner can add members."});const u=await User.findOne({email:(req.body.email||"").toLowerCase().trim()});if(!u)return res.status(404).json({message:"No account found for that email."});if(!p.members.some(x=>String(x)===String(u._id)))p.members.push(u._id);await p.save();res.json(await getProject(p._id,req.userId))}));
app.post("/api/projects/:id/tasks",auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({message:"Project not found."});if(!p.members.some(x=>String(x)===String(req.userId)))return res.status(403).json({message:"Access denied."});if(!req.body.title?.trim())return res.status(400).json({message:"Task title is required."});p.tasks.push({title:req.body.title.trim(),description:req.body.description||"",status:["todo","progress","done"].includes(req.body.status)?req.body.status:"todo",priority:["Low","Medium","High"].includes(req.body.priority)?req.body.priority:"Medium",assignee:req.body.assignee||null,dueDate:req.body.dueDate||null});await p.save();res.status(201).json(await getProject(p._id,req.userId))}));
app.patch("/api/projects/:id/tasks/:taskId",auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({message:"Project not found."});if(!p.members.some(x=>String(x)===String(req.userId)))return res.status(403).json({message:"Access denied."});const t=p.tasks.id(req.params.taskId);if(!t)return res.status(404).json({message:"Task not found."});for(const k of ["title","description","priority","dueDate","assignee"])if(req.body[k]!==undefined)t[k]=req.body[k]||null;if(req.body.status&&["todo","progress","done"].includes(req.body.status))t.status=req.body.status;await p.save();res.json(await getProject(p._id,req.userId))}));
app.delete("/api/projects/:id/tasks/:taskId",auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({message:"Project not found."});if(String(p.owner)!==String(req.userId))return res.status(403).json({message:"Only owner can delete tasks."});const t=p.tasks.id(req.params.taskId);if(!t)return res.status(404).json({message:"Task not found."});t.deleteOne();await p.save();res.json(await getProject(p._id,req.userId))}));
app.post("/api/projects/:id/tasks/:taskId/comments",auth,asyncRoute(async(req,res)=>{const p=await Project.findById(req.params.id);if(!p)return res.status(404).json({message:"Project not found."});if(!p.members.some(x=>String(x)===String(req.userId)))return res.status(403).json({message:"Access denied."});const t=p.tasks.id(req.params.taskId);if(!t)return res.status(404).json({message:"Task not found."});if(!req.body.text?.trim())return res.status(400).json({message:"Comment cannot be empty."});const u=await User.findById(req.userId);t.comments.push({user:u._id,name:u.name,text:req.body.text.trim()});await p.save();res.json(await getProject(p._id,req.userId))}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:"Server error. Check server logs."})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(process.env.PORT||5001,()=>console.log(`Project tool running at http://localhost:${process.env.PORT||5001}`));
